# Generated by Django 5.0.6 on 2024-07-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('government_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_due_date', models.DateField()),
                ('debt_id', models.UUIDField(unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
