# Generated by Django 3.2.25 on 2024-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20240702_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='status',
        ),
        migrations.AddField(
            model_name='debt',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
